# Generated by Django 4.0.2 on 2022-02-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(upload_to='upload_file'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
