# Generated by Django 4.0.2 on 2022-02-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_newspaper_content_alter_newspaper_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_file/'),
        ),
    ]
