# Generated by Django 4.0.2 on 2022-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_newspaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(default=1, upload_to='upload_file/'),
            preserve_default=False,
        ),
    ]
